services:
  api:
    build: .
    volumes:
      - .:/app
      - temp_pdfs:/app/temp_pdfs  # Mount temp_pdfs volume
      - faiss_indices:/app/faiss_indices  # Mount faiss_indices volume
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: myapi.settings
    env_file:
      - .env
    networks:
      - my_network

  redis:
    image: redis:6.0.16-alpine
    ports:
      - "6380:6379"  # Exposing Redis on host port 6380 to avoid conflicts with local Redis
    networks:
      - my_network

  celery_worker:
    build: .
    command: celery -A myapi worker --loglevel=info
    volumes:
      - .:/app
      - temp_pdfs:/app/temp_pdfs  # Mount temp_pdfs volume
      - faiss_indices:/app/faiss_indices  # Mount faiss_indices volume
    depends_on:
      - redis
      - api
    environment:
      REDIS_URL: redis://redis:6379/0
    env_file:
      - .env
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  temp_pdfs:  # Define temp_pdfs volume
  faiss_indices:  # Define faiss_indices volume  