# Generated by Django 5.1.6 on 2025-02-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255)),
                ('pdf_name', models.CharField(max_length=255)),
                ('history', models.JSONField(default=list)),
            ],
            options={
                'unique_together': {('client_id', 'pdf_name')},
            },
        ),
    ]
