# Generated by Django 5.1.6 on 2025-02-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_app', '0002_chathistory_summary_alter_chathistory_client_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Unique identifier for the user session.', max_length=100)),
                ('role', models.CharField(help_text='Role of the message sender (user or assistant).', max_length=50)),
                ('content', models.TextField(help_text='Content of the message.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the message.')),
            ],
        ),
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(help_text='Unique identifier for the client.', max_length=100)),
                ('pdf_name', models.CharField(help_text='Name of the PDF file.', max_length=255)),
                ('file_path', models.CharField(help_text='Path to the FAISS index file.', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='ChatHistory',
        ),
    ]
